Slack/Slack.jss.recipe

Now that @killaquam updated his pkg recipe to use CFBundleVersion, I think we should update our EA/SG pair to do the same.

Slack CFBundleVersion

---

Slack/Slack.jss.recipe

Parent recipe author can't make up his mind.
(https://github.com/autopkg/killahquam-recipes/commit/668cec6610313ce25a
ea10382568008e5fdec206)

Switching back to CFBundleShortVersionString.

---

R/R.jss.recipe
R/RExtensionAttribute.xml
R/RSmartGroupTemplate.xml

My changes include OS requirements, and changing over to an EA for
version tracking, since R.app doesn’t provide a nice version number.

Update R recipe.

---

1Password/1Password.jss.recipe

Current 1Password version is 6.2.1

incremented 1Password to v6

---

Adobe Acrobat Reader DC/Adobe Acrobat Reader DC.jss.recipe

Change the pkg name from something along the lines of AcroRdrDC_1501020060_MUI.pkg to Adobe Acrobat Reader DC-15.010.20060.pkg which more closely matches existing recipes.

Update Adobe Acrobat Reader DC.jss.recipe

---

Box Sync/Box Sync.jss.recipe

https://github.com/autopkg/hansen-m-recipes/blob/master/Box/BoxSync.pkg.
recipe#L89

Parent recipe uses CFBundleVersion:

---

Adobe Acrobat DC/Adobe Acrobat DCSmartGroupTemplate.xml

changed the priority numbers to be sequential to fix smart group criteria

Update Adobe Acrobat DCSmartGroupTemplate.xml

---

GitHub Desktop/GitHub Desktop.jss.recipe

Adding 10.12.x to the `OS_REQUIREMENTS` value.

Update GitHub Desktop.jss.recipe

---

OmniFocus/OmniFocus.jss.recipe
OmniGraffle/OmniGraffle.jss.recipe
OmniOutliner/OmniOutliner.jss.recipe
OmniPlan/OmniPlan.jss.recipe

Added more detailed information about the process of specifying which version of Omni Group apps you wish to add to your JSS.
Also see #96.

Updated Omni Group app descriptions to clarify overrides.

---

Tableau Desktop/Tableau Desktop.jss.recipe

Updating Tableau Desktop OS requirements to include 10.12.x

Update Tableau Desktop.jss.recipe

---

Compressor/Compressor.jss.recipe
Final Cut Pro/Final Cut Pro.jss.recipe
GarageBand/GarageBand.jss.recipe
Keynote/Keynote.jss.recipe
Logic Pro X/Logic Pro X.jss.recipe
MainStage 3/MainStage 3.jss.recipe
Microsoft Remote Desktop/Microsoft Remote Desktop.jss.recipe
Motion/Motion.jss.recipe
Numbers/Numbers.jss.recipe
Pages/Pages.jss.recipe
Parallels Desktop/Parallels Desktop.jss.recipe
Xcode/Xcode.jss.recipe
coconutBattery/coconutBattery.jss.recipe
iBooks Author/iBooks Author.jss.recipe
iMovie/iMovie.jss.recipe

Updated JSS recipes for coconutBattery, Compressor, Final Cut Pro, GarageBand, iBooks Author, iMovie, Keynote, Logic Pro X, MainStage, Microsoft Remote Desktop, Motion, Numbers, Pages, Parallels Desktop, and Xcode to reflect current OS_REQUIREMENTS from vendors. Updated SELF_SERVICE_DESCRIPTION entries to better reflect vendor-provided copy when available or appropriate.

updated OS_REQUIREMENTS for macOS Sierra support, updated SELF_SERVICE_DESCRIPTION

---

Audacity/Audacity.jss.recipe

Added note about Audacity now requiring PKG variable.

---

Microsoft Excel/Microsoft Excel.jss.recipe
Microsoft OneNote/Microsoft OneNote.jss.recipe
Microsoft Outlook/Microsoft Outlook.jss.recipe
Microsoft PowerPoint/Microsoft PowerPoint.jss.recipe
Microsoft Word/Microsoft Word.jss.recipe

Added High Sierra to OS requirements for Office recipes

---

PolicyTemplate.xml

Added support for the Self service display name as well as reinstall button.

Updated PolicyTemplate for JSS 10.2

---

Skype For Business/Skype For Business.jss.recipe

Adding Mojave package Compatibility to the Skype for Business JSS recipe

Adding Mojave Compatibility

---

Adobe Acrobat Reader DC/Adobe Acrobat Reader DC.jss.recipe

Updated the OS Requirements/OS Limitations to the current documented specs:  https://helpx.adobe.com/reader/system-requirements.html

Update Adobe Reader DC OS Requirements

---

Proximity/Proximity.jss.recipe
Sequel Pro/Sequel Pro.jss.recipe

Update for #176. Thanks to @grahampugh for catching this.

Corrected pathname to pkg_path in two recipes

---

Skype/Skype.jss.recipe

Adding Mojave OS requirements. This is working in our environment with the latest version of Skype

Mojave Skype

---

PyCharm CE/PyCharm CE.jss.recipe
Quicksilver/Quicksilver.jss.recipe

These recipes require the `pkg_path` key.

pkg_path key required in these recipes.

---

Skype For Business/Skype For Business.jss.recipe
Skype/Skype.jss.recipe

In order to install Skype and Skype for Business on the latest macOs,
this commit adds it to the `OS_REQUIREMENTS`.

Add 10.15 to OS Requirements

---

Firefox/Firefox.jss.recipe
Google Chrome/Google Chrome.jss.recipe
Parallels Desktop/Parallels Desktop.jss.recipe

- updated `OS_REQUIREMENTS` to reflect current vendor specifications

updated OS_REQUIREMENTS

---

Skype/Skype.jss.recipe

Added the pkg_path argument for the JSSImporter processor.

Update Skype.jss recipe

---

Google Chrome/Google Chrome.jss.recipe

Update Google Chrome.jss.recipe

---

Microsoft Remote Desktop/Microsoft Remote Desktop.jss.recipe

Update Microsoft Remote Desktop.jss.recipe

---

README.md

- fixed nested list indentation
- removed duplicate package category

fixed nested list indentation

---

validate_recipes.py

Made some changes to subprocess in order to fix reliance on Python 2.
Also disabled parent recipe search function, since `autopkg search` has been nerfed by GitHub lately. Will need to manually verify submitted recipe parents are in the autopkg org.

Update validation script for Python 3
