autopkg/jss-recipes

Casper Suite/Casper Suite.jss.recipe
The novaksam Casper Suite recipe contains a postinstall script that’ll
repair the folder icon.
=> Changing the Casper Suite pkg recipe.

Adobe Acrobat Pro/Adobe Acrobat Pro.jss.recipe
Removing OS requirements since Acrobat XI can be installed on 10.6.8+ and Acrobat X can be installed on 10.5 or 10.6.
=> Update Adobe Acrobat Pro.jss.recipe

Google Chrome/Google Chrome.jss.recipe
Added 
<key>OS_REQUIREMENTS</key>
<string>10.11.x,10.10.x, 10.9.x</string>
for Chrome 50: https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html
=> Updated OS_REQUIREMENTS for Chrome 50

Oracle Java 8 JDK/Oracle Java 8 JDKExtensionAttribute.xml
due to sorting error when the version went above 100, it's still returning 92 in the EA.
=> fix for oracle jdk 8 extension attribute

1Password/1Password.jss.recipe
Adding macOS Sierra to 1Password `OS_REQUIREMENTS` value.
=> adding macOS Sierra to 1Password OS_REQUIREMENTS value

Oracle Java 8 JDK/Oracle Java 8 JDKExtensionAttribute.xml
The previous EA would sort the file listing like this:
$ ls /Library/Java/JavaVirtualMachines | grep "jdk" | grep "1.8" | sed 's/.jdk//' | sed 's/jdk//' | sort -r
1.8.0_92
1.8.0_111
1.8.0_101
Which would mean that 1.8.0_101 returns instead of 1.8.0_111.
=> fixes issue in EA where the sorting of the versions does not work

GitHub Desktop/GitHub Desktop.jss.recipe
Updating OS requirements to support 10.13 High Sierra. Tested the package and confirmed it installs correctly on a 10.13 machines via JSS policy.
=> Update GitHub Desktop.jss.recipe

OracleJava7/OracleJava7ExtensionAttribute.xml, OracleJava8/OracleJava8ExtensionAttribute.xml, OracleJava9/OracleJava9ExtensionAttribute.xml
All three major versions of Java install at the same location and use the same version key, so their extension attributes for versioning should be identical.
=> Standardized Java (JRE) extension attributes

iTerm2/iTerm2.jss.recipe
The smart group currently doesn't match the iTerm.app, so no computers are added.
=> Updated iTerm2 Recipe's JSS_INVENTORY_NAME

MySQLWorkBench/MySQLWorkBench.jss.recipe
Fix for Issue #162. The parent recipe changed the casing of the name to match the casing in the actual app name, which has resulted in the JSS recipe not being able to find the parent and failing to run/make overrides/etc. Might also be worth updating the name of the JSS recipe/folder but I don't know what impact (though if no one has noticed this recipe is broken for that long maybe no one will care).
=> Fix ParentRecipe

Suspicious Package/Suspicious Package.jss.recipe
Parent Recipes were updated for new package distribution.
Updating to support those.
=> Adding the required pkg_path argument

Sketch/Sketch.jss.recipe
Updated `OS_REQUIREMENTS` for current Sketch build (52.4 and later require macOS High Sierra 10.13.4 or newer and support macOS Mojave, according to https://www.sketchapp.com/support/requirements/system-requirements and https://blog.sketchapp.com/macos-mojave-brings-dark-mode-to-sketch-cccbf51f4164).
=> updated OS_REQUIREMENTS for current Sketch build

Zoom/Zoom.jss.recipe
Added JSS_INVENTORY_NAME definition to match the app bundle name of "zoom.us.app". Excluding this caused Auto Update Magic child recipes to incorrectly identify Application Title as "Zoom.app" in the autoupdate smart group, and never scope needed patches.
=> added JSS_INVENTORY_NAME definition

Proximity/Proximity.jss.recipe, Sequel Pro/Sequel Pro.jss.recipe
Got angry messages about JSSimporter requiring the missing argument pkg_path.
=> pkg_path fix for parent pkg recipe change

1Password/1Password.jss.recipe
- updated OS_REQUIREMENTS for 1Password 7
- removed MAJOR_VERSION string (parent recipe only targets 1Password 7)
=> updated OS_REQUIREMENTS for 1Password 7

Skitch/Skitch.jss.recipe
I have conformed Skitch works with macOS 10.14.6, and added 10.14.x to the OS requirements.
=> Added Mojave for Skitch

Keynote/Keynote.jss.recipe, Numbers/Numbers.jss.recipe, Pages/Pages.jss.recipe
All iWork apps now require macOS 10.14 Mojave or later. I know that in the past there's been hesitation to change the OS_REQUIREMENTS since the Mac running AutoPkg may be an older version, but I suspect it would be best to have overrides change the default app requirement as needed to account for differences in local infrastructure.
=> updated OS_REQUIREMENTS for iWork apps

Adobe Acrobat DC/Adobe Acrobat DC.jss.recipe
Per Adobe doc: https://helpx.adobe.com/acrobat/system-requirements.html
Follow up to #194.
=> Set OS requirements for Acrobat DC to 10.12+

1Password/1Password.jss.recipe, Bartender/Bartender.jss.recipe
Recently set up a new 10.15 machine, Bartender and 1Password package requirements are out of date.
=> Add 10.15 and 10.14 to package requirements for Bartender and 1Password

CFBundleVersionExtensionAttribute.xml, CFBundleVersionSmartGroupTemplate.xml, Zoom/Zoom.jss.recipe
- changed `GROUP_TEMPLATE` to CFBundleSmartGroupTemplate.xml (Zoom application no longer reports version string in a format compatible with AutoPkg)
- added extension attribute using CFBundleVersionExtensionAttribute.xml
- removed `JSS_INVENTORY_NAME` definition (no longer required with extension attribute addition)
- changed `NAME` to zoom.us to match the application bundle name (so it's compatible with the EA template; alternative would be to make a separate template file just for Zoom to accommodate the app name/product name disparity, but this felt cleaner)
- increased `MinimumVersion` to 1.1 (to match parent recipe)
- added space to computer group name in CFBundleVersionExtensionAttribute.xml for improved legibility
=> switched Zoom recipe to use CFBundleVersion

GitHub Desktop/GitHub Desktop.jss.recipe
Added 10.15.x and 10.14.x, and removed 10.9.x, per Github Desktop's current system requirements. https://help.github.com/en/desktop/getting-started-with-github-desktop/installing-github-desktop
=> Update Github Desktop OS requirements

Adobe Acrobat Reader DC/Adobe Acrobat Reader DC.jss.recipe
Removed the `PkgCopier` Step from the recipe as it doesn't appear needed...and is failing to copy for me.  Taking it out, the recipe successfully completes.
If I'm missing something, feel free to let me know...
=> AdobeReaderDC:  Removed the `PkgCopier` Step

AdobeFlashPlayer/AdobeFlashPlayer.jss.recipe, Docker Toolbox/Docker Toolbox.jss.recipe, Office2011Update/Office2011Update-DisabledAllQuit.jss.recipe, Office2011Update/Office2011Update.jss.recipe, validate_recipes.py
Docker Toolbox, Adobe Flash Player, and Microsoft Office 2011 are no longer maintained, and therefore their jss recipes are no longer useful. Will remove the recipes from the repo at a later date.
Also updated the validator script to skip deprecated recipes and include PowerPoint alongside its other Office exemptions, due to having more than just the JSSImporter processor.
=> Deprecate obsolete recipes and update validation script

Citrix Receiver/Citrix Receiver.jss.recipe, Google Drive/Google Drive.jss.recipe, MySQLWorkBench/MySQLWorkBench.jss.recipe, Wireshark/Wireshark.jss.recipe
The parent recipe has been copied to homebysix-recipes in order to prepare for cgerke-recipes deprecation. For details, see: autopkg/cgerke-recipes#37
=> Change parent recipe for cgerke-recipes deprecation

Parallels Desktop/Parallels Desktop.jss.recipe
- added `PLATFORM_ARCH` note to description to match [upstream recipe changes](https://github.com/autopkg/homebysix-recipes/pull/408), as a Parallels recipe with major version 15 doesn't work if you specify `PLATFORM_ARCH`, and major version 16 doesn't work if you _omit_ `PLATFORM_ARCH`
- removed `MAJOR_VERSION` and `OS_REQUIREMENTS` input variables
=> added PLATFORM_ARCH note

AirServer/AirServer.jss.recipe, Eclipse/Eclipse-Luna.jss.recipe, GSP5/GSP5.jss.recipe, Jin/Jin.jss.recipe, OpenEmu/OpenEmu.jss.recipe, VirtualBox/VirtualBox.jss.recipe, jss_helper/jss_helper.jss.recipe, yo/yo.jss.recipe
The sheagcraig-recipes repository is being deprecated (details here: https://github.com/autopkg/sheagcraig-recipes/issues/71). Many working and/or serviceable recipes have already been [copied](https://github.com/autopkg/homebysix-recipes/pull/414) to the homebysix-recipes repo. This PR changes the parent recipes in your repo to point to the homebysix-recipes version of any affected recipes.
In addition to updating trust info, users of the changed recipes will need to ensure the homebysix-recipes repo is added to their AutoPkg environment (`autopkg repo-add homebysix-recipes`).
=> Adjust parent recipes for sheagcraig-recipes repo deprecation

.pre-commit-config.yaml, 1Password/1Password.jss.recipe, Firefox/Firefox.jss.recipe, GarageBand/GarageBand.jss.recipe, Google Chrome/Google Chrome.jss.recipe, Keynote/Keynote.jss.recipe, Microsoft Remote Desktop/Microsoft Remote Desktop.jss.recipe, Numbers/Numbers.jss.recipe, OmniFocus/OmniFocus.jss.recipe, OmniGraffle/OmniGraffle.jss.recipe, OmniOutliner/OmniOutliner.jss.recipe, OmniPlan/OmniPlan.jss.recipe, Pages/Pages.jss.recipe, Skype/Skype.jss.recipe, Xcode/Xcode.jss.recipe, coconutBattery/coconutBattery.jss.recipe, iMovie/iMovie.jss.recipe
Specify `11.x,10.16.x` for Big Sur, and update OS requirements for selected apps.
=> Update app requirements and make Big Sur version syntax consistent

Comic Life 3/Comic Life 3.jss.recipe
"The sheagcraig-recipes repository is deprecated.
Details: https://github.com/autopkg/sheagcraig-recipes/issues/71
Alternative ComicLife3 recipes exist in the tallfunnyjew-recipes repository."
=> Update parent recipe due to deprecation

Google Drive/Google Drive.jss.recipe
Parent recipe is deprecated: https://github.com/autopkg/homebysix-recipes/blob/master/Google/GoogleDrive.download.recipe#L24-L27
=> Change parent recipe due to deprecation

MacadminsPython/MacadminsPython.jss.recipe
Follows the upstream download recipe and includes a key for targeting pre-release versions. Let me know if you need any changes.
Thanks!
=> MacadminsPython - INCLUDE_PRERELEASES key + description

MSOffice2016VersionChecker/MSOffice2016VersionChecker.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+
